### ISSUE TITLE
Type reference not being recognized

### ISSUE THREAD

**Issue by genzzo** [kgajera/stripe-event-types#3]
When referencing the package I get an error saying

> Namespace '"stripe".Stripe' has no exported member 'DiscriminatedEvent'.

I am working on a nestjs project and this is what my code looks like

```ts
import { Controller, Post, Req } from "@nestjs/common";
import { Request } from "express";
import Stripe from "stripe";

/// <reference types="stripe-event-types" />

@Controller("stripe")
export class StripeController {
  private readonly stripe: Stripe;

  constructor() {
    this.stripe = new Stripe("secret", {
      apiVersion: "2022-08-01",
    });
  }

  @Post()
  async webhook(@Req() req: Request) {
    const event = this.stripe.webhooks.constructEvent(
      req.body,
      req.headers["stripe-signature"],
      "secret"
    ) as Stripe.DiscriminatedEvent; // <--- error here
    console.log(event);
  }
}
```
I managed to fix the type issue by directly importing the package instead of referencing
```ts
import "stripe-event-types";
```
However, I now get this error when building or starting the dev server

> Error: Cannot find module 'stripe-event-types'

**Comment by kgajera** [comment]
@genzzo Can you try moving `/// <reference types="stripe-event-types" />` to the top of the file above the imports? That should fix the issue.

From TypeScript's docs (https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html):
>  Triple-slash directives are only valid at the top of their containing file. A triple-slash directive can only be preceded by single or multi-line comments, including other triple-slash directives. If they are encountered following a statement or a declaration they are treated as regular single-line comments, and hold no special meaning.

Let me know if you still have issues.

**Comment by genzzo** [comment]
Oh apologies my bad I did not know about that.
All works well now thanks a lot!

**Comment by JackHammer29** [comment]
Still getting this issue with both the stripe slash reference, and the import

<img width="705" alt="image" src="https://github.com/kgajera/stripe-event-types/assets/18452529/a7933915-73ef-4f15-985d-cb3ac12dfbd5">

<img width="588" alt="image" src="https://github.com/kgajera/stripe-event-types/assets/18452529/e0a308d8-5443-46fc-9f22-bfcd7c4eb873">


EDIT:

Fixed by taking the import out, but still have to leave the eslint exception in that allows triple slash type imports
